### ISSUE TITLE
local install fails with error message

### ISSUE THREAD

**Issue by username1290** [cfpb/design-manual#628]
getting this error when trying to run `npm start`:

```
➜  design-manual git:(gh-pages) ✗ npm start

> design-manual@1.0.0 start /Users/myusername/github/design-manual
> parallelshell "bundle exec jekyll serve --watch --baseurl ''" "grunt watch"

child_process.js:424
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:424:11)
    at spawn (child_process.js:536:16)
    at /Users/myusername/github/design-manual/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/myusername/github/design-manual/node_modules/parallelshell/index.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-manual@1.0.0 start: `parallelshell "bundle exec jekyll serve --watch --baseurl ''" "grunt watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-manual@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myusername/.npm/_logs/2019-07-12T21_27_03_002Z-debug.log
```

running:
```
node v12.6.0
npm 6.9.0
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
jekyll 3.8.5
grunt-cli: The grunt command line interface (v1.3.2)
```

**Comment by Scotchester** [comment]
I think parallelshell has been causing problems for a while, but to be transparent with you, @sogen, this repo will soon be deprecated, so we probably won't be fixing this.

**Comment by username1290** [comment]
thanks, great work on the new repo!
